import streamlit as st
import json
import os

def load_app_settings():
    """Load application settings from file"""
    settings_file = "data/app_settings.json"
    if os.path.exists(settings_file):
        try:
            with open(settings_file, 'r') as f:
                return json.load(f)
        except:
            pass
    return {'language': 'English', 'theme': 'Modern', 'offline_mode': False}

def save_app_settings(settings):
    """Save application settings to file"""
    settings_file = "data/app_settings.json"
    try:
        # Ensure data directory exists
        os.makedirs(os.path.dirname(settings_file), exist_ok=True)
        with open(settings_file, 'w') as f:
            json.dump(settings, f, indent=2)
        return True
    except Exception as e:
        print(f"Error saving settings: {e}")
        return False

def get_text(key, language=None):
    """Get localized text based on language setting"""
    # Get language from session state or settings if not provided
    if language is None:
        language = st.session_state.get('app_language')
        if language is None:
            settings = load_app_settings()
            language = settings.get('language', 'English')
            st.session_state['app_language'] = language
    
    translations = {
        'English': {
            # Navigation
            'dashboard': 'Dashboard',
            'assessment': 'Assessment', 
            'resources': 'Resources',
            'tracker': 'Tracker',
            'analytics': 'Analytics',
            'settings': 'Settings',
            
            # Header
            'app_title': 'EduScan Somalia',
            'app_subtitle': 'Professional Learning Assessment Application',
            'online_mode': 'Online Mode',
            'offline_mode': 'Offline Mode',
            
            # Assessment Form
            'assessment_form': 'Assessment Form',
            'empowering_student_success': 'Empowering Student Success',
            'student_information': 'Student Information',
            'student_name': 'Student Name',
            'grade_level': 'Grade Level',
            'academic_performance': 'Academic Performance',
            'behavioral_social_indicators': 'Behavioral & Social Indicators',
            'math_score': 'Math Score (0-100)',
            'reading_score': 'Reading Score (0-100)',
            'writing_score': 'Writing Score (0-100)',
            'attendance': 'School Attendance (%)',
            'behavior_rating': 'Behavior Rating',
            'literacy_level': 'Literacy Level',
            'analyze_learning_risk': 'Analyze Learning Risk',
            'clear_form': 'Clear Form',
            'assessment_results': 'AI Assessment Results',
            'comprehensive_assessment': 'Comprehensive learning assessment completed for',
            'risk_level': 'Risk Level',
            'recommendations': 'Recommendations',
            'low_risk': 'Low Risk',
            'medium_risk': 'Medium Risk', 
            'high_risk': 'High Risk',
            
            # Teacher Resources
            'teacher_resources': 'Teacher Resources',
            'supporting_every_teacher': 'Supporting Every Teacher, Reaching Every Student',
            'inclusive_classroom_excellence': 'Inclusive Classroom Excellence',
            'professional_collaboration': 'Professional Collaboration',
            'engaging_learning_strategies': 'Engaging Learning Strategies',
            'assessment_innovation': 'Assessment Innovation',
            'teaching_guides': 'Teaching Guides & Strategies',
            'lesson_plans': 'Lesson Plan Creation',
            'educational_games': 'Educational Games',
            'real_life_activities': 'Real-Life Learning Activities',
            'saved_resources': 'Saved Resources',
            
            # Parent Tracker
            'parent_tracker': 'Parent Tracker',
            'strengthening_connections': 'Strengthening Home-School Connections',
            'daily_observation_log': 'Daily Observation Log',
            'child_name': "Child's Name",
            'observation_date': 'Observation Date',
            'academic_observations': 'Academic Observations',
            'homework_completion': 'Homework Completion (%)',
            'reading_time': 'Reading Time (minutes)',
            'focus_level': 'Focus Level',
            'subjects_struggled': 'Subjects Struggled With',
            'behavioral_observations': 'Behavioral Observations',
            'mood_rating': 'Mood Rating',
            'sleep_hours': 'Sleep Hours',
            'energy_level': 'Energy Level',
            'learning_wins': 'Learning Wins Today',
            'challenges_faced': 'Challenges Faced',
            'save_observation': 'Save Observation',
            'progress_insights': 'Progress Insights',
            
            # Educational Content
            'educational_content': 'Educational Content',
            'building_educational_excellence': 'Building Educational Excellence Through Research',
            'evidence_based_insights': 'Evidence-Based Insights for Learning Success',
            'comprehensive_educational_research': 'Comprehensive educational research and resources to support effective learning interventions',
            'educational_excellence_in_action': 'Educational Excellence in Action',
            'global_best_practices': 'Global Best Practices',
            'international_standards': 'International standards and methods adapted for Somali educational environments',
            'learning_science': 'Learning Science',
            'neuroscience_cognitive_research': 'Neuroscience and cognitive research on how children learn most effectively',
            'intervention_studies': 'Intervention Studies',
            'evidence_based_strategies': 'Evidence-based strategies for supporting students with learning challenges',
            'cultural_adaptation': 'Cultural Adaptation',
            'implementing_inclusive_education': 'Research on implementing inclusive education in diverse cultural contexts',
            'educational_research_impact': 'Educational Research Impact',
            'content_categories': 'Content Categories',
            'choose_content_type': 'Choose content type:',
            'research_overview': 'Research Overview',
            'types_learning_difficulties': 'Types of Learning Difficulties',
            'early_intervention': 'Early Intervention',
            'academic_resources': 'Academic Resources',
            'technology_tools': 'Technology Tools',
            'support_strategies': 'Support Strategies',
            'target_audience': 'Target Audience',
            'content_for': 'Content for:',
            'teachers': 'Teachers',
            'parents': 'Parents',
            'administrators': 'Administrators',
            'all': 'All',
            
            # Teacher Resources - Additional
            'excellence_in_education': 'Excellence in Somali Education',
            'empowering_teachers': 'Empowering Teachers with Evidence-Based Learning Support Strategies',
            'professional_development': 'Professional development resources designed for inclusive classroom success',
            'create_learning_environments': 'Create learning environments where every student thrives through differentiated instruction',
            'build_strong_partnerships': 'Build strong partnerships with families and specialists for comprehensive student support',
            'implement_culturally_responsive': 'Implement culturally responsive teaching methods that connect with Somali students',
            'use_multiple_assessment': 'Use multiple assessment methods to accurately gauge student progress and needs',
            'teaching_excellence_showcase': 'Teaching Excellence Showcase',
            'resource_categories': 'Resource Categories',
            'choose_resource_type': 'Choose resource type:',
            'differentiated_learning_strategies': 'Differentiated Learning Strategies',
            'inclusive_classroom_tips': 'Inclusive Classroom Tips',
            'intervention_techniques': 'Intervention Techniques',
            'assessment_strategies': 'Assessment Strategies',
            'activity_generator': 'Activity Generator',
            'teaching_strategies': 'Teaching Strategies',
            'learning_activities': 'Learning Activities',
            'assessment_tools': 'Assessment Tools',
            'classroom_management': 'Classroom Management',
            'differentiation_techniques': 'Differentiation Techniques',
            'technology_integration': 'Technology Integration',
            'cultural_sensitivity': 'Cultural Sensitivity',
            'difficulty_focus': 'Difficulty Focus',
            'target_difficulty': 'Target difficulty:',
            'reading_language': 'Reading/Language',
            'mathematics': 'Mathematics',
            'writing': 'Writing',
            'attention_focus': 'Attention/Focus',
            'memory': 'Memory',
            'processing_speed': 'Processing Speed',
            'social_skills': 'Social Skills',
            'behavioral_issues': 'Behavioral Issues',
            
            # Parent Tracker - Additional
            'supporting_childs_learning': "Supporting Your Child's Learning Journey",
            'family_centered_approach': 'Family-Centered Approach to Educational Success',
            'empowering_parents_tools': 'Empowering parents with tools and insights to support their child\'s academic growth at home',
            'daily_tracking': 'Daily Tracking',
            'monitor_child_progress': 'Monitor your child\'s learning progress with simple, effective tools',
            'parent_empowerment': 'Parent Empowerment',
            'gain_insights_strategies': 'Gain insights and strategies to support learning at home',
            'school_partnership': 'School Partnership',
            'build_communication_bridges': 'Build strong communication bridges with your child\'s teachers',
            'student_success': 'Student Success',
            'celebrate_achievements': 'Celebrate achievements and address challenges together',
            'student_progress_stories': 'Student Progress Stories',
            'child_selection': 'Child Selection',
            'tracking': 'Tracking',
            'dashboard_options': 'Dashboard Options',
            'choose_view': 'Choose view:',
            'daily_entry': 'Daily Entry',
            'progress_tracking': 'Progress Tracking',
            'weekly_summary': 'Weekly Summary',
            'observations_log': 'Observations Log',
            
            # Rating options
            'poor': 'Liita',
            'below_average': 'Ka hooseeya Celceliska',
            'average': 'Celcelis ah',
            'good': 'Fiican',
            'excellent': 'Aad u Fiican',
            
            # Additional missing translations - Somali
            'please_correct_errors': 'Fadlan sax khaladaadka soo socda:',
            'risk_assessment_gauge': 'Cabbirka Qiimaynta Khatarta',
            'student_performance_profile': 'Astaanta Waxqabadka Ardayga',
            'personalized_intervention_recommendations': 'Talooyinka Faragelinta Gaarka ah',
            'assessment_summary': 'Soo-koobka Qiimaynta',
            'please_enter_child_name': 'Fadlan geli magaca ilmahaaga ee geeddi-socodka si aad u bilowdo dabagalka.',
            'daily_observation_entry': 'Gelitaanka Indho-indhaynta Maalinlaha ah',
            'recording_observations_for': 'Duubitaanka indho-indhayntii',
            'on': 'maalinta',
            'behavioral_emotional': 'Dhaqan & Dareen',
            'statistics': 'Tirokoobka',
            'neuroscience': 'Cilmiga Neerfaha',
            'impact_studies': 'Daraasadaha Saameynta',
            'learning_difficulties_statistics': 'Tirokoobka Caqabadaha Barashada',
            
            # Rating options
            'poor': 'Poor',
            'below_average': 'Below Average',
            'average': 'Average',
            'good': 'Good',
            'excellent': 'Excellent',
            
            # Additional missing translations
            'please_correct_errors': 'Please correct the following errors:',
            'risk_assessment_gauge': 'Risk Assessment Gauge',
            'student_performance_profile': 'Student Performance Profile',
            'personalized_intervention_recommendations': 'Personalized Intervention Recommendations',
            'assessment_summary': 'Assessment Summary',
            'please_enter_child_name': "Please enter your child's name in the sidebar to begin tracking.",
            'daily_observation_entry': 'Daily Observation Entry',
            'recording_observations_for': 'Recording observations for',
            'on': 'on',
            'behavioral_emotional': 'Behavioral & Emotional',
            'statistics': 'Statistics',
            'neuroscience': 'Neuroscience',
            'impact_studies': 'Impact Studies',
            'learning_difficulties_statistics': 'Learning Difficulties Statistics',
            'building_excellence_research': 'Building Educational Excellence Through Research',
            'global_best_practices': 'Global Best Practices',
            'learning_science': 'Learning Science',
            'intervention_studies': 'Intervention Studies',
            'cultural_adaptation': 'Cultural Adaptation',
            
            # Common
            'excellent': 'Excellent',
            'good': 'Good',
            'average': 'Average',
            'below_average': 'Below Average',
            'poor': 'Poor',
            'low': 'Low',
            'medium': 'Medium',
            'high': 'High',
        },
        'Somali': {
            # Navigation
            'dashboard': 'Xarunta Xogta',
            'assessment': 'Qiimayn',
            'resources': 'Agabka',
            'tracker': 'Dabagal',
            'analytics': 'Falanqayn',
            'settings': 'Dejinta',
            
            # Header
            'app_title': 'EduScan Somalia',
            'app_subtitle': 'Barnaamijka Qiimaynta Barashada Xirfadlayaasha',
            'online_mode': 'Hab Toos ah',
            'offline_mode': 'Hab Offline ah',
            
            # Assessment Form
            'assessment_form': 'Foomka Qiimaynta',
            'empowering_student_success': 'Xoojinta Guulaha Ardayda',
            'student_information': 'Macluumaadka Ardayga',
            'student_name': 'Magaca Ardayga',
            'grade_level': 'Heerka Fasalka',
            'academic_performance': 'Waxqabadka Tacliinta',
            'behavioral_social_indicators': 'Tilmaamaha Dhaqanka iyo Bulshada',
            'math_score': 'Dhibcaha Xisaabta (0-100)',
            'reading_score': 'Dhibcaha Akhriska (0-100)', 
            'writing_score': 'Dhibcaha Qorista (0-100)',
            'attendance': 'Soo Gaadhitaanka Dugsiga (%)',
            'behavior_rating': 'Qiimaynta Dhaqanka',
            'literacy_level': 'Heerka Aqrinta',
            'analyze_learning_risk': 'Falanqee Khatarta Barashada',
            'clear_form': 'Nadiifi Foomka',
            'assessment_results': 'Natiijada Qiimaynta AI',
            'comprehensive_assessment': 'Qiimayn dhamaystiran oo barasho ah ayaa loo dhammeeyay',
            'risk_level': 'Heerka Khatarta',
            'recommendations': 'Talooyinka',
            'low_risk': 'Khatar Yar',
            'medium_risk': 'Khatar Dhexdhexaad ah',
            'high_risk': 'Khatar Weyn',
            
            # Teacher Resources
            'teacher_resources': 'Agabka Macalliminta',
            'supporting_every_teacher': 'Taageeridda Macallin kasta, Gaadhitaanka Arday Kasta',
            'inclusive_classroom_excellence': 'Fiicnaan Fasal oo Dhammaystiran',
            'professional_collaboration': 'Iskaashi Xirfadeed',
            'engaging_learning_strategies': 'Xeeladaha Barashada Soo Jiidashada leh',
            'assessment_innovation': 'Hal-abuurka Qiimaynta',
            'teaching_guides': 'Tilmaamaha iyo Xeeladaha Waxbarashada',
            'lesson_plans': 'Abuurista Qorshaha Casharrada',
            'educational_games': 'Ciyaaraha Waxbarasho',
            'real_life_activities': 'Dhaqdhaqaaqyada Nolosha Dhabta ah',
            'saved_resources': 'Agabka la Keydsaday',
            
            # Parent Tracker
            'parent_tracker': 'Dabagalka Waalidka',
            'strengthening_connections': 'Xoojinta Xiriirka Guriga-Dugsiga',
            'daily_observation_log': 'Diiwaanka Indho-indhaynta Maalinta',
            'child_name': 'Magaca Ilmaha',
            'observation_date': 'Taariikhda Indho-indhaynta',
            'academic_observations': 'Indho-indhaynta Tacliinta',
            'homework_completion': 'Dhammaystirka Hawsha Guriga (%)',
            'reading_time': 'Waqtiga Akhriska (daqiiqado)',
            'focus_level': 'Heerka Diiradda',
            'subjects_struggled': 'Maadooyinka la Tacban yahay',
            'behavioral_observations': 'Indho-indhaynta Dhaqanka',
            'mood_rating': 'Qiimaynta Dareenka',
            'sleep_hours': 'Saacadaha Hurdada',
            'energy_level': 'Heerka Tamarta',
            'learning_wins': 'Guusha Barashada Maanta',
            'challenges_faced': 'Caqabadaha la Kulmay',
            'save_observation': 'Kaydi Indho-indhaynta',
            'progress_insights': 'Aragtiyo Horumarka',
            
            # Educational Content
            'educational_content': 'Waxyaabaha Waxbarasho',
            'building_educational_excellence': 'Dhisidda Fiicnaanta Waxbarasho iyada oo loo marayo Cilmi-baaris',
            'evidence_based_insights': 'Aragtiyo ku Salaysan Caddayn si loo Gaadho Guulaha Barashada',
            'comprehensive_educational_research': 'Cilmi-baaris dhamaystiran oo waxbarasho ah iyo agab taageerid ah si loo xoojiyo faragelinta waxtar leh',
            'educational_excellence_in_action': 'Fiicnaanta Waxbarasho ee Ficilka ah',
            'global_best_practices': 'Hab-maamuuska Ugu Fiican Adduunka',
            'international_standards': 'Heerarka caalamiga ah iyo hababka loo waafajiyay jadada waxbarasho ee Soomaaliya',
            'learning_science': 'Sayniska Barashada',
            'neuroscience_cognitive_research': 'Cilmi-baarista maskaxda iyo fekerka oo ku saabsan sida caruurtu u bartaan si ugu waxtar badan',
            'intervention_studies': 'Daraasadaha Faragelinta',
            'evidence_based_strategies': 'Xeeladaha ku salaysan caddeyn si loo taageero ardayda leh caqabadaha barashada',
            'cultural_adaptation': 'La-qabsiga Dhaqanka',
            'implementing_inclusive_education': 'Cilmi-baaris ku saabsan hirgelinta waxbarasho dhammaystiran oo ku habboon jadad dhaqameed oo kala duwan',
            'educational_research_impact': 'Saameynta Cilmi-baarista Waxbarasho',
            'content_categories': 'Qaybaha Waxyaabaha',
            'choose_content_type': 'Dooro nooca waxyaabaha:',
            'research_overview': 'Dulmar Cilmi-baaris',
            'types_learning_difficulties': 'Noocyada Caqabadaha Barashada',
            'early_intervention': 'Faragelin Hore',
            'academic_resources': 'Agabka Tacliinta',
            'technology_tools': 'Qalab Teknoolajiyeed',
            'support_strategies': 'Xeeladaha Taageerada',
            'target_audience': 'Dadka Bartilmaameedka ah',
            'content_for': 'Waxyaabaha loogu talagalay:',
            'teachers': 'Macallimiin',
            'parents': 'Waalidiinta',
            'administrators': 'Maamuleyaasha',
            'all': 'Dhammaan',
            
            # Teacher Resources - Additional Somali
            'excellence_in_education': 'Fiicnaanta Waxbarasho Soomaaliya',
            'empowering_teachers': 'Xoojinta Macalliminta iyada oo la adeegsanayo Xeeladaha Taageerada Barashada ee ku Salaysan Caddeyn',
            'professional_development': 'Agabka horumarinta xirfadeed ee loo qorsheeyay guulaha fasal dhammaystiran',
            'create_learning_environments': 'Samee deegaan barasho oo arday kasta ku kobco iyada oo la adeegsanayo tadris kala duwan',
            'build_strong_partnerships': 'Dhis iskaashi adag oo qoysaska iyo takhasusyada la sameeyo si loo helo taageero arday oo dhamaystiran',
            'implement_culturally_responsive': 'Hirgelinta hababka waxbarashada ee dhaqan-ogaanta leh ee la xidhiidha ardayda Soomaaliyeed',
            'use_multiple_assessment': 'Isticmaal hababka qiimayn ee kala duwan si si sax ah loogu cabbiro horumarka iyo baahiyaha ardayda',
            'teaching_excellence_showcase': 'Bandhigga Fiicnaanta Waxbarashada',
            'resource_categories': 'Qaybaha Agabka',
            'choose_resource_type': 'Dooro nooca agabka:',
            'differentiated_learning_strategies': 'Xeeladaha Barashada ee Kala Duwanaanta',
            'inclusive_classroom_tips': 'Talooyinka Fasal Dhammaystiran',
            'intervention_techniques': 'Farsamada Faragelinta',
            'assessment_strategies': 'Xeeladaha Qiimaynta',
            'activity_generator': 'Dhaliyaha Dhaqdhaqaaqa',
            'teaching_strategies': 'Xeeladaha Waxbarashada',
            'learning_activities': 'Dhaqdhaqaaqyada Barashada',
            'assessment_tools': 'Qalab Qiimayn',
            'classroom_management': 'Maamaynta Fasalka',
            'differentiation_techniques': 'Farsamada Kala-soocida',
            'technology_integration': 'Isku-dhafka Teknoolajiyada',
            'cultural_sensitivity': 'Dareen-ka Dhaqanka',
            'difficulty_focus': 'Diiradda Caqabadaha',
            'target_difficulty': 'Caqabadda bartilmaameedka ah:',
            'reading_language': 'Akhriska/Luqadda',
            'mathematics': 'Xisaabta',
            'writing': 'Qorista',
            'attention_focus': 'Diiradda/Feejignaan',
            'memory': 'Xusuusta',
            'processing_speed': 'Xawaaraha Farsamaynta',
            'social_skills': 'Xirfadaha Bulshada',
            'behavioral_issues': 'Arrimaha Dhaqanka',
            
            # Parent Tracker - Additional Somali
            'supporting_childs_learning': 'Taageeridda Safarka Barashada Ilmahaaga',
            'family_centered_approach': 'Hab Qoys ku Aasaasan si loo Gaadho Guulaha Waxbarasho',
            'empowering_parents_tools': 'Xoojinta waalidka iyada oo la adeegsanayo qalab iyo aragtiyo si ay u taageeraan koboca tacliinta ilmahooda guriga',
            'daily_tracking': 'Dabagalka Maalinlaha ah',
            'monitor_child_progress': 'La-soco horumarka barashada ilmahaaga iyada oo la adeegsanayo qalab fudud oo waxtar leh',
            'parent_empowerment': 'Xoojinta Waalidka',
            'gain_insights_strategies': 'Hel aragtiyo iyo xeeladaho si aad ugu taageerto barashada guriga',
            'school_partnership': 'Iskaashiga Dugsiga',
            'build_communication_bridges': 'Dhis buundooyin wadahadal oo xooggan oo aad la samayso macalliminta ilmahaaga',
            'student_success': 'Guulaha Ardayga',
            'celebrate_achievements': 'U dabaal-deg guulaha oo wada xalli caqabadaha',
            'student_progress_stories': 'Sheekoooyinka Horumarka Ardayda',
            'child_selection': 'Doorashada Ilmaha',
            'tracking': 'Dabagal',
            'dashboard_options': 'Doorashooyinka Xarunta Xogta',
            'choose_view': 'Dooro aragtida:',
            'daily_entry': 'Gelinsa Maalinlaha ah',
            'progress_tracking': 'Dabagalka Horumarka',
            'weekly_summary': 'Soo-koobka Toddobaadlaha ah',
            'observations_log': 'Diiwaanka Indho-indhaynta',
            
            # Common
            'excellent': 'Aad u Fiican',
            'good': 'Fiican',
            'average': 'Celcelis ah',
            'below_average': 'Ka hooseeya Celceliska',
            'poor': 'Liita',
            'low': 'Hoose',
            'medium': 'Dhexdhexaad',
            'high': 'Sare',
        },
        'Arabic': {
            # Navigation
            'dashboard': 'لوحة التحكم',
            'assessment': 'التقييم',
            'resources': 'الموارد',
            'tracker': 'المتتبع',
            'analytics': 'التحليلات',
            'settings': 'الإعدادات',
            
            # Header
            'app_title': 'EduScan Somalia',
            'app_subtitle': 'تطبيق التقييم التعليمي المهني',
            'online_mode': 'الوضع المتصل',
            'offline_mode': 'الوضع غير المتصل',
            
            # Assessment Form
            'assessment_form': 'نموذج التقييم',
            'empowering_student_success': 'تمكين نجاح الطلاب',
            'student_information': 'معلومات الطالب',
            'student_name': 'اسم الطالب',
            'grade_level': 'مستوى الصف',
            'academic_performance': 'الأداء الأكاديمي',
            'behavioral_social_indicators': 'المؤشرات السلوكية والاجتماعية',
            'math_score': 'درجة الرياضيات (0-100)',
            'reading_score': 'درجة القراءة (0-100)',
            'writing_score': 'درجة الكتابة (0-100)', 
            'attendance': 'حضور المدرسة (%)',
            'behavior_rating': 'تقييم السلوك',
            'literacy_level': 'مستوى محو الأمية',
            'analyze_learning_risk': 'تحليل مخاطر التعلم',
            'clear_form': 'مسح النموذج',
            'assessment_results': 'نتائج تقييم الذكاء الاصطناعي',
            'comprehensive_assessment': 'تم إكمال تقييم تعليمي شامل لـ',
            'risk_level': 'مستوى المخاطر',
            'recommendations': 'التوصيات',
            'low_risk': 'مخاطر منخفضة',
            'medium_risk': 'مخاطر متوسطة',
            'high_risk': 'مخاطر عالية',
            
            # Teacher Resources
            'teacher_resources': 'موارد المعلمين',
            'supporting_every_teacher': 'دعم كل معلم، الوصول إلى كل طالب',
            'inclusive_classroom_excellence': 'التميز في الفصل الدراسي الشامل',
            'professional_collaboration': 'التعاون المهني',
            'engaging_learning_strategies': 'استراتيجيات التعلم الجذابة',
            'assessment_innovation': 'ابتكار التقييم',
            'teaching_guides': 'أدلة واستراتيجيات التدريس',
            'lesson_plans': 'إنشاء خطط الدروس',
            'educational_games': 'الألعاب التعليمية',
            'real_life_activities': 'أنشطة التعلم الواقعية',
            'saved_resources': 'الموارد المحفوظة',
            
            # Parent Tracker
            'parent_tracker': 'متتبع الوالدين',
            'strengthening_connections': 'تعزيز الروابط بين المنزل والمدرسة',
            'daily_observation_log': 'سجل الملاحظة اليومية',
            'child_name': 'اسم الطفل',
            'observation_date': 'تاريخ الملاحظة',
            'academic_observations': 'الملاحظات الأكاديمية',
            'homework_completion': 'إنجاز الواجبات المنزلية (%)',
            'reading_time': 'وقت القراءة (دقائق)',
            'focus_level': 'مستوى التركيز',
            'subjects_struggled': 'المواد التي واجه صعوبة فيها',
            'behavioral_observations': 'الملاحظات السلوكية',
            'mood_rating': 'تقييم المزاج',
            'sleep_hours': 'ساعات النوم',
            'energy_level': 'مستوى الطاقة',
            'learning_wins': 'انتصارات التعلم اليوم',
            'challenges_faced': 'التحديات المواجهة',
            'save_observation': 'حفظ الملاحظة',
            'progress_insights': 'رؤى التقدم',
            
            # Educational Content
            'educational_content': 'المحتوى التعليمي',
            'building_educational_excellence': 'بناء التميز التعليمي من خلال البحث',
            'evidence_based_insights': 'رؤى قائمة على الأدلة لنجاح التعلم',
            'comprehensive_educational_research': 'بحث تعليمي شامل وموارد لدعم التدخلات التعليمية الفعالة',
            'educational_excellence_in_action': 'التميز التعليمي في العمل',
            'global_best_practices': 'أفضل الممارسات العالمية',
            'international_standards': 'المعايير الدولية والأساليب المكيفة للبيئات التعليمية الصومالية',
            'learning_science': 'علم التعلم',
            'neuroscience_cognitive_research': 'أبحاث علم الأعصاب والإدراك حول كيفية تعلم الأطفال بشكل أكثر فعالية',
            'intervention_studies': 'دراسات التدخل',
            'evidence_based_strategies': 'استراتيجيات قائمة على الأدلة لدعم الطلاب ذوي تحديات التعلم',
            'cultural_adaptation': 'التكيف الثقافي',
            'implementing_inclusive_education': 'بحث حول تنفيذ التعليم الشامل في سياقات ثقافية متنوعة',
            'educational_research_impact': 'أثر البحث التعليمي',
            'content_categories': 'فئات المحتوى',
            'choose_content_type': 'اختر نوع المحتوى:',
            'research_overview': 'نظرة عامة على البحث',
            'types_learning_difficulties': 'أنواع صعوبات التعلم',
            'early_intervention': 'التدخل المبكر',
            'academic_resources': 'الموارد الأكاديمية',
            'technology_tools': 'أدوات التكنولوجيا',
            'support_strategies': 'استراتيجيات الدعم',
            'target_audience': 'الجمهور المستهدف',
            'content_for': 'المحتوى لـ:',
            'teachers': 'المعلمين',
            'parents': 'الآباء',
            'administrators': 'الإداريين',
            'all': 'الجميع',
            
            # Additional missing translations - Arabic
            'please_correct_errors': 'يرجى تصحيح الأخطاء التالية:',
            'risk_assessment_gauge': 'مقياس تقييم المخاطر',
            'student_performance_profile': 'ملف أداء الطالب',
            'personalized_intervention_recommendations': 'توصيات التدخل المخصصة',
            'assessment_summary': 'ملخص التقييم',
            'please_enter_child_name': 'يرجى إدخال اسم طفلك في الشريط الجانبي لبدء التتبع.',
            'daily_observation_entry': 'إدخال الملاحظة اليومية',
            'recording_observations_for': 'تسجيل الملاحظات لـ',
            'on': 'في',
            'behavioral_emotional': 'السلوكي والعاطفي',
            'statistics': 'الإحصائيات',
            'neuroscience': 'علم الأعصاب',
            'impact_studies': 'دراسات الأثر',
            'learning_difficulties_statistics': 'إحصائيات صعوبات التعلم',
            
            # Common
            'excellent': 'ممتاز',
            'good': 'جيد',
            'average': 'متوسط',
            'below_average': 'أقل من المتوسط',
            'poor': 'ضعيف',
            'low': 'منخفض',
            'medium': 'متوسط',
            'high': 'عالي',
        }
    }
    
    return translations.get(language, translations['English']).get(key, key)